# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. إعداد بيئة Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # 2. تثبيت حزم Flutter
      - name: Install dependencies
        run: flutter pub get

      # 3. إنشاء ملف .env وهمي لمنع خطأ flutter analyze
      - name: Create dummy .env file
        run: touch .env

      # 4. التحقق من جودة وتنسيق الكود
      - name: Analyze project source
        run: flutter analyze

      # 5. تشغيل اختبارات Flutter
      - name: Run tests
        run: flutter test
